// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUfHqwMx8qvXtuEg8WPnLIHhRoHW1Gbyc',
    appId: '1:878242959994:web:76957c183cda55a83ee1c3',
    messagingSenderId: '878242959994',
    projectId: 'fitness-app-1892c',
    authDomain: 'fitness-app-1892c.firebaseapp.com',
    storageBucket: 'fitness-app-1892c.firebasestorage.app',
    measurementId: 'G-7BQCF6N7S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7MfP3WOBYdz2bY8FLSSU6DqtCVpV8XZM',
    appId: '1:878242959994:android:975b4f957885bbdd3ee1c3',
    messagingSenderId: '878242959994',
    projectId: 'fitness-app-1892c',
    storageBucket: 'fitness-app-1892c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuojSvv4wm5dR8pV2lOl6_I6M1xB99avI',
    appId: '1:878242959994:ios:22f05ae45564d11e3ee1c3',
    messagingSenderId: '878242959994',
    projectId: 'fitness-app-1892c',
    storageBucket: 'fitness-app-1892c.firebasestorage.app',
    iosBundleId: 'com.example.termProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuojSvv4wm5dR8pV2lOl6_I6M1xB99avI',
    appId: '1:878242959994:ios:22f05ae45564d11e3ee1c3',
    messagingSenderId: '878242959994',
    projectId: 'fitness-app-1892c',
    storageBucket: 'fitness-app-1892c.firebasestorage.app',
    iosBundleId: 'com.example.termProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUfHqwMx8qvXtuEg8WPnLIHhRoHW1Gbyc',
    appId: '1:878242959994:web:fbdb1b76b717ba9a3ee1c3',
    messagingSenderId: '878242959994',
    projectId: 'fitness-app-1892c',
    authDomain: 'fitness-app-1892c.firebaseapp.com',
    storageBucket: 'fitness-app-1892c.firebasestorage.app',
    measurementId: 'G-JZZT8XC7HK',
  );

}